### PR TITLE
fix unix builds without curl

### PR DESCRIPTION
**Pull request by gantsevdenis**
Hm I am not sure this is what is the plan, but this fixes master build
offending commit: https://github.com/c3lang/c3c/commit/0be291e0d72b32db21e26bc48f638fbbf8ca5083
Otherwise the build fails:
```
/home/den/sources/c3c/src/utils/fetch_msvc.c:191:23: error: implicit declaration of function ‘download_file’ [-Wimplicit-function-declaration]
  191 |     const char *err = download_file(url, "", dst);
```

### CODE REVIEW

**Comment by lerno** [comment]
@ManuLinares can you have a look at this?

**Comment by ManuLinares** [comment]
I've done another PR to solve this https://github.com/c3lang/c3c/pull/2904
Thanks for bringing attention to this.

A simple `#if FETCH_AVAILABLE` and a message should do the trick cleanly.
```
#else
void fetch_msvc(BuildOptions *options)
{
	error_exit("Failed to find Windows SDK.\n"
			   "Windows applications cannot be cross-compiled without it.\n"
			   "This build of c3c lacks cURL support and cannot download the SDK automatically.\n"
			   "Please provide the SDK path manually using --winsdk.");
}
#endif
```

**Comment by lerno** [comment]
Thank you for taking to finding this error and making this PR @gantsevdenis. I'll go with Manu's smaller PR for this, but it's great that you found the issue.

**Comment by gantsevdenis** [comment]
no pb, the other PR makes more sense
