### PR TITLE
Don't use -Werror

### PR DESCRIPTION
**Pull request by data-man**
gcc version 10.2.0
>file_utils.c:131:2: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  131 |  strncpy(path, full_path, path_len + 1);

### CODE REVIEW

**Comment by lerno** [comment]
Thank you, but I've fixed the usage instead. Can you verify that it works on 10.2.0?

**Comment by data-man** [comment]
Thanks!

> Can you verify that it works on 10.2.0?

`c3c/src/compiler/llvm_codegen.c:13:14: error: variable ‘severerity_name’ set but not used [-Werror=unused-but-set-variable]
   13 |  const char *severerity_name = "unknown";
      |              ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors`

**Comment by lerno** [comment]
@data-man I think that one is fixed now as well. If you have a list of warnings, paste it here and I'll fix them all.

**Comment by data-man** [comment]
> I think that one is fixed now as well.

No. The same error for 7f3963cbc5b2f25b108865dc37630234f0837037 commit.

**Comment by data-man** [comment]
> If you have a list of warnings, paste it here and I'll fix them all.

> c3c/src/compiler/llvm_codegen_expr.c:1257:15: warning: ‘len’ may be used uninitialized in this function [-Wmaybe-uninitialized]

> c3c/src/compiler/llvm_codegen_expr.c:1266:11: warning: ‘parent_load_value’ may be used uninitialized in this function [-Wmaybe-uninitialized]

> c3c/src/compiler/llvm_codegen_expr.c:1851:2: warning: ‘val’ may be used uninitialized in this function [-Wmaybe-uninitialized]

**Comment by data-man** [comment]
@lerno BTW, can you enable Discussions for this repo (or for c3docs)?
For non-Discord users? :)

**Comment by lerno** [comment]
@data-man Those errors all seem like hideously poor flow analysis by GCC, or GCC does not pick up __attribute__((noreturn)) for some weird reason. I'll have to try to see if I can replicate this.

I'm not sure about the discussions, but there is a forum here: https://c3.handmade.network/forums

**Comment by data-man** [comment]
@lerno 
If you dislike my patch as is I propose to add CMake option for it.
Somethink like `-DC3_IGNORE_COMPILING_WARNINGS`.

**Comment by lerno** [comment]
It's more like there should not even be these warnings and I've now tested with GCC on Ubuntu at least and I can't reproduce, even when explicitly adding those flags. What's your environment?

**Comment by lerno** [comment]
This is the version of gcc I've used to test: gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0

**Comment by data-man** [comment]
>  What's your environment?

Artix Linux, gcc 10.2.0-6
$ gcc --version -v

>Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix

**Comment by lerno** [comment]
I'm now at Artix Linux with exactly that environment and I can´t reproduce those errors. Do you use CMake to build? What version of cmake?

**Comment by data-man** [comment]
> Do you use CMake to build? What version of cmake?

Yes. 3.20.1 version.

> I can´t reproduce those errors.

With Release build type?

```sh
mkdir -p build-rel
cd build-rel
cmake -DCMAKE_BUILD_TYPE=Release ..
```

**Comment by data-man** [comment]
Yes, Debug build hasn't errors.

**Comment by lerno** [comment]
@data-man Thanks, I tracked down one issue which was use disappearing in non debug builds, which was ok. But the others were simply false positives thanks to GCCs poor data flow analysis, so I removed that particular warning (maybe-uninitialized). It should now work even in release for you, correct?

**Comment by data-man** [comment]
> It should now work even in release for you, correct?

Yes, thank you!
