### ISSUE TITLE
link fails when compiling with `--x86cpu=native` flag

### ISSUE THREAD

**Issue by puni073** [c3lang/c3c#2361]
0.7.3 works with `--x86cpu=native` but 0.7.4 does not.

main.c3
```
fn void main() {
}
```
`c3c compile --x86cpu=native main.c3`
```
/usr/bin/ld: /tmp/c3cXh5cEdp/obj/linux-x64/std.math.math_rt.o: in function `round':
/home/runner/c3/lib/std/math/math.c3:447:(.text.roundevenf[roundevenf]+0x29): undefined reference to `roundf'
/usr/bin/ld: /home/runner/c3/lib/std/math/math.c3:447:(.text.roundeven[roundeven]+0x29): undefined reference to `round'
collect2: error: ld returned 1 exit status
Failed to link executable './main' using command 'cc -o ./main -rdynamic -pthread /tmp/c3cXh5cEdp/obj/linux-x64/std_collections_list.std.os.backtrace.Backtrace.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.ascii.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.types.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.dstring.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.mem.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.string.conv.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.string.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.mem.allocator.o /tmp/c3cXh5cEdp/obj/linux-x64/std.core.builtin.o /tmp/c3cXh5cEdp/obj/linux-x64/std.io.file.o /tmp/c3cXh5cEdp/obj/linux-x64/std.io.os.o /tmp/c3cXh5cEdp/obj/linux-x64/std.io.o /tmp/c3cXh5cEdp/obj/linux-x64/libc.o /tmp/c3cXh5cEdp/obj/linux-x64/std.os.backtrace.o /tmp/c3cXh5cEdp/obj/linux-x64/std.os.process.o /tmp/c3cXh5cEdp/obj/linux-x64/std.os.posix.o /tmp/c3cXh5cEdp/obj/linux-x64/std.os.linux.o /tmp/c3cXh5cEdp/obj/linux-x64/std.math.math_rt.o /tmp/c3cXh5cEdp/obj/linux-x64/std.math.o /tmp/c3cXh5cEdp/obj/linux-x64/std.atomic.o /tmp/c3cXh5cEdp/obj/linux-x64/main.o -ldl'.
```
`c3c --version`
```
C3 Compiler Version:       0.7.4
Installed directory:       /home/runner/c3
Git Hash:                  f0142e3b1a091a479cbc3cdc1a4beebdc0e18fcc
Backends:                  LLVM
LLVM version:              17.0.6
LLVM default target:       x86_64-pc-linux-gnu
```

**Comment by lerno** [comment]
I made a full patch to 0.7.4 for this. I assume it works now?

**Comment by puni073** [comment]
It works. Thank you.
